[package]
name = "af3_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "af3_core"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
pyo3 = { version = "0.22.5", features = ["auto-initialize"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

